# Lab | Chains in LangChain

## Outline

* LLMChain
* Sequential Chains
  * SimpleSequentialChain
  * SequentialChain
* Router Chain

In [27]:
import warnings
warnings.filterwarnings('ignore')

In [28]:
import os

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

OPENAI_API_KEY  = os.getenv('OPENAI_API_KEY')
HUGGINGFACEHUB_API_TOKEN = os.getenv('HUGGINGFACEHUB_API_TOKEN')

In [29]:
#!pip install pandas

In [30]:
import pandas as pd
df = pd.read_csv('data/Data.csv')

In [31]:
df.head()

                   Product                                             Review
0     Queen Size Sheet Set  I ordered a king size set. My only criticism w...
1   Waterproof Phone Pouch  I loved the waterproof sac, although the openi...
2      Luxury Air Mattress  This mattress had a small hole in the top of i...
3           Pillows Insert  This is the best throw pillow fillers on Amazo...
4  Milk Frother Handheld\n   I loved this product. But they only seem to l...

In [39]:
df.shape

(7, 2)

## LLMChain

In [32]:
!pip install langchain_community

Requirement already satisfied: langchain_community in /opt/anaconda3/lib/python3.13/site-packages (0.3.29)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.75 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.3.75)
Requirement already satisfied: langchain<2.0.0,>=0.3.27 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.3.27)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.0.39)
Requirement already satisfied: requests<3,>=2.32.5 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.32.5)
Requirement already satisfied: PyYAML>=5.3 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (3.11.10)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (9.0.0)
Requirement already satisfied: dataclasses-json<0.7,>=0.6.7 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.10.1)
Requirement already satisfied: langsmith>=0.1.125 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.4.21)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.4.1)
Requirement already satisfied: numpy>=2.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.1.3)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.18.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /opt/anaconda3/lib/python3.13/site-packages (from dataclasses-json<0.7,>=0.6.7->langchain_community) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from dataclasses-json<0.7,>=0.6.7->langchain_community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /opt/anaconda3/lib/python3.13/site-packages (from langchain<2.0.0,>=0.3.27->langchain_community) (0.3.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/anaconda3/lib/python3.13/site-packages (from langchain<2.0.0,>=0.3.27->langchain_community) (2.10.3)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.75->langchain_community) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.75->langchain_community) (4.12.2)
Requirement already satisfied: packaging>=23.2 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.75->langchain_community) (24.2)
Requirement already satisfied: jsonpointer>=1.9 in /opt/anaconda3/lib/python3.13/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<2.0.0,>=0.3.75->langchain_community) (2.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain_community) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain_community) (2.27.1)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.1.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain_community) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain_community) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain_community) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain_community) (2025.8.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.6.7->langchain_community) (1.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain_community) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain_community) (0.23.0)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (4.7.0)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (1.3.0)

In [33]:
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains import LLMChain

In [34]:
#Replace None by your own value and justify
llm = ChatOpenAI(temperature=1)

In [46]:
prompt = ChatPromptTemplate.from_template(
    "You are a product description generator. Given the following product details, generate a compelling product description:\n\nProduct Name: {product}\nProduct Description:"
)

In [47]:

chain = LLMChain(llm=llm, prompt=prompt)

In [48]:
product = "Luxury Air Mattress"
chain.run(product)

"Experience ultimate comfort and relaxation with our Luxury Air Mattress. Made with high-quality materials and advanced technology, this air mattress offers superior support and plushness for a truly restful night's sleep. Whether you're camping in the great outdoors or hosting guests at home, this luxurious air mattress will provide the perfect combination of comfort and durability. Say goodbye to uncomfortable nights and hello to the ultimate in sleeping luxury with our Luxury Air Mattress."

## SimpleSequentialChain

In [49]:
from langchain.chains import SimpleSequentialChain

In [50]:
llm = ChatOpenAI(temperature=0.9)

# prompt template 1
first_prompt = ChatPromptTemplate.from_template(
    "You are a product description generator. Given the following product details, generate a compelling product description:\n\nProduct Name: {product}\nProduct Description:"
)

# Chain 1
chain_one = LLMChain(llm=llm, prompt=first_prompt)

In [51]:

# prompt template 2
second_prompt = ChatPromptTemplate.from_template(
    "You are a marketing expert. Given the following product description, generate a catchy marketing slogan:\n\nProduct Description: {product_description}\nMarketing Slogan:"
)
# chain 2
chain_two = LLMChain(llm=llm, prompt=second_prompt)

In [52]:
overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],
                                             verbose=True
                                            )

In [53]:
overall_simple_chain.run(product)

> Entering new SimpleSequentialChain chain...
Experience the ultimate comfort and relaxation with our Luxury Air Mattress. Made with high-quality materials and innovative design, this air mattress provides the perfect balance of support and cushioning for a restful night's sleep. Whether you're hosting guests, camping outdoors, or simply need a temporary sleeping solution, this luxurious air mattress will exceed your expectations. Say goodbye to uncomfortable nights and hello to the perfect sleep solution with our Luxury Air Mattress.
"Sleep like royalty on our Luxury Air Mattress - where comfort meets innovation for the ultimate restful night's sleep!"

> Finished chain.

'"Sleep like royalty on our Luxury Air Mattress - where comfort meets innovation for the ultimate restful night\'s sleep!"'

In [54]:
df.head()

                   Product                                             Review
0     Queen Size Sheet Set  I ordered a king size set. My only criticism w...
1   Waterproof Phone Pouch  I loved the waterproof sac, although the openi...
2      Luxury Air Mattress  This mattress had a small hole in the top of i...
3           Pillows Insert  This is the best throw pillow fillers on Amazo...
4  Milk Frother Handheld\n   I loved this product. But they only seem to l...

In [ ]:
    product = "Queen Size Sheet Set"

    llm = ChatOpenAI(temperature=0.9)

    # prompt template 1
    first_prompt = ChatPromptTemplate.from_template(
        "You are a product description generator. Given the following product details, generate a compelling product description:\n\nProduct Name: {product}\nProduct Description:"
    )

    # Chain 1
    chain_one = LLMChain(llm=llm, prompt=first_prompt)


    # prompt template 2
    second_prompt = ChatPromptTemplate.from_template(
        "You are a marketing expert. Given the following product description, generate a catchy marketing slogan:\n\nProduct Description: {product_description}\nMarketing Slogan:"
    )
    # chain 2
    chain_two = LLMChain(llm=llm, prompt=second_prompt)

    overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],
                                                verbose=True
                                                )

    overall_simple_chain.run(product)

> Entering new SimpleSequentialChain chain...
Indulge in luxury every night with our Queen Size Sheet Set. Made from the finest materials, these sheets are soft, breathable, and incredibly comfortable. The perfect addition to any bedroom, these sheets are designed to provide a cozy and peaceful sleep environment. With a variety of colors to choose from, you can easily match these sheets to any decor style. Treat yourself to the ultimate in bedtime comfort with our Queen Size Sheet Set.
"Sleep like royalty every night with our luxurious Queen Size Sheet Set - where comfort meets style!"

> Finished chain.

'"Sleep like royalty every night with our luxurious Queen Size Sheet Set - where comfort meets style!"'

In [56]:
    product = "Waterproof Phone Pouch"

    llm = ChatOpenAI(temperature=0.9)

    # prompt template 1
    first_prompt = ChatPromptTemplate.from_template(
        "You are a product description generator. Given the following product details, generate a compelling product description:\n\nProduct Name: {product}\nProduct Description:"
    )

    # Chain 1
    chain_one = LLMChain(llm=llm, prompt=first_prompt)


    # prompt template 2
    second_prompt = ChatPromptTemplate.from_template(
        "You are a marketing expert. Given the following product description, generate a catchy marketing slogan:\n\nProduct Description: {product_description}\nMarketing Slogan:"
    )
    # chain 2
    chain_two = LLMChain(llm=llm, prompt=second_prompt)

    overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],
                                                verbose=True
                                                )

    overall_simple_chain.run(product)

> Entering new SimpleSequentialChain chain...
Keep your phone safe and dry with our Waterproof Phone Pouch! Whether you're lounging by the pool, hitting the beach, or caught in a sudden downpour, this pouch will protect your device from water, sand, and dirt. With a transparent front and a secure seal, you can still use your phone while it's safely enclosed. Say goodbye to worries about accidental spills or drops - our Waterproof Phone Pouch has got you covered. Don't let water ruin your day, stay connected and protected with this must-have accessory!
"Stay dry, stay connected - with our Waterproof Phone Pouch, your phone is protected!"

> Finished chain.

'"Stay dry, stay connected - with our Waterproof Phone Pouch, your phone is protected!"'

**Repeat the above twice for different products**

## SequentialChain

In [57]:
from langchain.chains import SequentialChain

In [65]:
df.Review[5]

"Je trouve le goût médiocre. La mousse ne tient pas, c'est bizarre. J'achète les mêmes dans le commerce et le goût est bien meilleur...\nVieux lot ou contrefaçon !?"

In [71]:
llm = ChatOpenAI(temperature=0.9)


first_prompt = ChatPromptTemplate.from_template(
  "Translate the following product review in English to German:\n\n{review}\n\nGerman Translation:"
)

chain_one = LLMChain(llm=llm, prompt=first_prompt, 
                     output_key="german_translation"
                    )

In [72]:
second_prompt = ChatPromptTemplate.from_template(
    "Summarize the following product review in one sentence:\n\n{review}\n\nSummary:"
)

chain_two = LLMChain(llm=llm, prompt=second_prompt, 
                     output_key="summary"
                    )

In [73]:
# prompt template 3: translate to english or other language
third_prompt = ChatPromptTemplate.from_template(
    "Translate the following product review to English:\n\n{review}\n\nEnglish Translation:"
)
# chain 3: input= Review and output= language
chain_three = LLMChain(llm=llm, prompt=third_prompt,
                       output_key="english_translation"
                      )

In [74]:

# prompt template 4: follow up message that take as inputs the two previous prompts' variables
fourth_prompt = ChatPromptTemplate.from_template(
        "Given the following translations and summaries, create a follow-up message:\n\nGerman Translation: {german_translation}\nSummary: {summary}\n\nFollow-up Message:"
)
chain_four = LLMChain(llm=llm, prompt=fourth_prompt,
                      output_key="follow_up_message"
                     )

In [77]:
# overall_chain: input= Review 
# and output= English_Review,summary, followup_message
overall_chain = SequentialChain(
    chains=[chain_one, chain_two, chain_three, chain_four],
    input_variables=["review"],
    output_variables=["german_translation", "summary", "follow_up_message"],
    verbose=True
)

In [81]:
review = df.Review[3]
overall_chain(review)

> Entering new SequentialChain chain...

> Finished chain.

{'review': 'This is the best throw pillow fillers on Amazon. I’ve tried several others, and they’re all cheap and flat no matter how much fluffing you do. Once you toss these in the dryer after you remove them from the vacuum sealed shipping material, they fluff up great',
 'german_translation': 'Dies sind die besten Füllkissen für Dekokissen auf Amazon. Ich habe schon mehrere andere ausprobiert, und sie sind alle billig und flach, egal wie sehr man sie aufschüttelt. Wenn man sie nach dem Entfernen aus der vakuumversiegelten Versandverpackung in den Trockner wirft, fluffen sie großartig auf.',
 'summary': 'These throw pillow fillers are superior to other options on Amazon, providing excellent fluffiness after a quick trip through the dryer.',
 'follow_up_message': "Thank you for the recommendation on the throw pillow fillers! I will definitely give them a try and see how they compare to the ones I currently have. It's great to hear that they fluff up so nicely after a quick trip through the dryer. I appreciate the tip!"}

In [82]:
review = df.Review[4]
overall_chain(review)

> Entering new SequentialChain chain...

> Finished chain.

{'review': "\xa0I loved this product. But they only seem to last a few months. The company was great replacing the first one (the frother falls out of the handle and can't be fixed). The after 4 months my second one did the same. I only use the frother for coffee once a day. It's not overuse or abuse. I'm very disappointed and will look for another. As I understand they will only replace once. Anyway, if you have one good luck.",
 'german_translation': 'Ich liebte dieses Produkt. Aber anscheinend halten sie nur ein paar Monate. Die Firma war großartig, den ersten (der Milchaufschäumer fällt aus dem Griff und kann nicht repariert werden) zu ersetzen. Nach 4 Monaten tat das zweite dasselbe. Ich benutze den Milchaufschäumer nur einmal am Tag für Kaffee. Es ist kein übermäßiger Gebrauch oder Missbrauch. Ich bin sehr enttäuscht und werde nach einem anderen suchen. Soweit ich weiß, ersetzen sie nur einmal. Wie auch immer, wenn Sie einen haben, viel Glück.',
 'summary': 'The reviewer loved the product but found that it only lasted a few months before the frother fell out of the handle, leading to disappointment and a need to find a new product.',
 'follow_up_message': "Thank you for sharing your experience with the product. It's unfortunate that it didn't last long for you, despite the company replacing it once. We appreciate your feedback and we hope you find a more durable alternative. If you have any other recommendations or feedback, please feel free to share. Thank you and good luck in your search for a new frother."}

In [ ]:
review = df.Review[5]
overall_chain(review)

# Why follow up message is sometimes in German and sometimes in English?

> Entering new SequentialChain chain...

> Finished chain.

{'review': "Je trouve le goût médiocre. La mousse ne tient pas, c'est bizarre. J'achète les mêmes dans le commerce et le goût est bien meilleur...\nVieux lot ou contrefaçon !?",
 'german_translation': 'Ich finde den Geschmack schlecht. Der Schaum hält nicht, das ist seltsam. Ich kaufe die gleichen im Laden und der Geschmack ist viel besser... Alte Charge oder Fälschung!?',
 'summary': "The reviewer finds the taste mediocre, the foam doesn't hold well, and suspects the product may be old or counterfeit compared to similar ones purchased in stores.",
 'follow_up_message': 'Sehr geehrte Kundin/Sehr geehrter Kunde,\n\nVielen Dank für Ihr Feedback zu unserem Produkt. Es tut uns leid zu hören, dass Sie mit dem Geschmack und der Qualität nicht zufrieden waren. Wir setzen uns dafür ein, dass unsere Produkte stets von höchster Qualität sind und werden Ihr Feedback daher an unser Qualitätsteam weiterleiten, um sicherzustellen, dass solche Probleme nicht erneut auftreten. Sollten Sie weitere Fragen oder Anliegen haben, zögern Sie bitte nicht, uns zu kontaktieren.\n\nMit freundlichen Grüßen,\nIhr Kundendienst-Team'}

In [91]:
print("Sehr geehrter Kunde,\n\nVielen Dank")

Sehr geehrter Kunde,

Vielen Dank

**Repeat the above twice for different products or reviews**

## Router Chain

In [94]:
physics_template = """You are a very smart physics professor. \
You are great at answering questions about physics in a concise\
and easy to understand manner. \
When you don't know the answer to a question you admit\
that you don't know.

Here is a question:
{input}"""


math_template = """You are a very good mathematician. \
You are great at answering math questions. \
You are so good because you are able to break down \
hard problems into their component parts, 
answer the component parts, and then put them together\
to answer the broader question.

Here is a question:
{input}"""

history_template = """You are a very good historian. \
You have an excellent knowledge of and understanding of people,\
events and contexts from a range of historical periods. \
You have the ability to think, reflect, debate, discuss and \
evaluate the past. You have a respect for historical evidence\
and the ability to make use of it to support your explanations \
and judgements.

Here is a question:
{input}"""


computerscience_template = """ You are a successful computer scientist.\
You have a passion for creativity, collaboration,\
forward-thinking, confidence, strong problem-solving capabilities,\
understanding of theories and algorithms, and excellent communication \
skills. You are great at answering coding questions. \
You are so good because you know how to solve a problem by \
describing the solution in imperative steps \
that a machine can easily interpret and you know how to \
choose a solution that has a good balance between \
time complexity and space complexity. 

Here is a question:
{input}"""

biology_template = """You are an excellent biologist. \
You have a deep understanding of living organisms, \
from the molecular and cellular level to entire ecosystems. \
You are skilled at observing patterns in nature, analyzing biological data, \
and explaining complex processes like evolution, genetics, physiology, and ecology. \
You can clearly communicate how life functions and adapts, \
and you make connections between different biological concepts \
to answer challenging questions.

Here is a question:
{input}"""

In [97]:
prompt_infos = [
    {
        "name": "physics", 
        "description": "Good for answering questions about physics", 
        "prompt_template": physics_template
    },
    {
        "name": "math", 
        "description": "Good for answering math questions", 
        "prompt_template": math_template
    },
    {
        "name": "History", 
        "description": "Good for answering history questions", 
        "prompt_template": history_template
    },
    {
        "name": "computer science", 
        "description": "Good for answering computer science questions", 
        "prompt_template": computerscience_template
    },
    {
        "name": "biology",
        "description": "Good for answering biology questions",
        "prompt_template": biology_template
    }
]

In [96]:
from langchain.chains.router import MultiPromptChain
from langchain.chains.router.llm_router import LLMRouterChain,RouterOutputParser
from langchain.prompts import PromptTemplate

In [98]:
llm = ChatOpenAI(temperature=0)

In [99]:
destination_chains = {}
for p_info in prompt_infos:
    name = p_info["name"]
    prompt_template = p_info["prompt_template"]
    prompt = ChatPromptTemplate.from_template(template=prompt_template)
    chain = LLMChain(llm=llm, prompt=prompt)
    destination_chains[name] = chain  
    
destinations = [f"{p['name']}: {p['description']}" for p in prompt_infos]
destinations_str = "\n".join(destinations)

In [100]:
default_prompt = ChatPromptTemplate.from_template("{input}")
default_chain = LLMChain(llm=llm, prompt=default_prompt)

In [101]:
MULTI_PROMPT_ROUTER_TEMPLATE = """Given a raw text input to a \
language model select the model prompt best suited for the input. \
You will be given the names of the available prompts and a \
description of what the prompt is best suited for. \
You may also revise the original input if you think that revising\
it will ultimately lead to a better response from the language model.

<< FORMATTING >>
Return a markdown code snippet with a JSON object formatted to look like:
```json
{{{{
    "destination": string \ name of the prompt to use or "DEFAULT"
    "next_inputs": string \ a potentially modified version of the original input
}}}}
```

REMEMBER: "destination" MUST be one of the candidate prompt \
names specified below OR it can be "DEFAULT" if the input is not\
well suited for any of the candidate prompts.
REMEMBER: "next_inputs" can just be the original input \
if you don't think any modifications are needed.

<< CANDIDATE PROMPTS >>
{destinations}

<< INPUT >>
{{input}}

<< OUTPUT (remember to include the ```json)>>"""

In [102]:
router_template = MULTI_PROMPT_ROUTER_TEMPLATE.format(
    destinations=destinations_str
)
router_prompt = PromptTemplate(
    template=router_template,
    input_variables=["input"],
    output_parser=RouterOutputParser(),
)

router_chain = LLMRouterChain.from_llm(llm, router_prompt)

In [103]:
chain = MultiPromptChain(router_chain=router_chain, 
                         destination_chains=destination_chains, 
                         default_chain=default_chain, verbose=True
                        )

In [104]:
chain.run("What is black body radiation?")

> Entering new MultiPromptChain chain...
physics: {'input': 'What is black body radiation?'}
> Finished chain.

"Black body radiation refers to the electromagnetic radiation emitted by a perfect black body, which is an idealized physical body that absorbs all incident electromagnetic radiation and emits radiation at all frequencies. The radiation emitted by a black body depends only on its temperature and follows a specific distribution known as Planck's law. This type of radiation is important in understanding concepts such as thermal radiation and the behavior of objects at different temperatures."

In [105]:
chain.run("what is 2 + 2")

> Entering new MultiPromptChain chain...
math: {'input': 'what is 2 + 2'}
> Finished chain.

'The answer to 2 + 2 is 4.'

In [ ]:
chain.run("Why does every cell in our body contain DNA?")

> Entering new MultiPromptChain chain...
biology: {'input': 'Why does every cell in our body contain DNA?'}
> Finished chain.

'Every cell in our body contains DNA because DNA is the genetic material that carries the instructions for the development, functioning, and reproduction of all living organisms. DNA contains the information needed to build and maintain an organism, including the proteins that make up our cells and tissues. \n\nHaving DNA in every cell ensures that each cell has the necessary genetic information to carry out its specific functions and to replicate itself accurately during cell division. This ensures that the genetic information is passed on to the next generation of cells. \n\nAdditionally, DNA is constantly being used by cells to carry out processes such as protein synthesis, cell division, and repair. Having DNA in every cell allows for the coordination of these processes and ensures that the organism functions properly as a whole. \n\nIn summary, every cell in our body contains DNA because it is essential for the proper functioning and development of all living organisms.'

In [108]:
chain.run("When do we reach AGI?")

> Entering new MultiPromptChain chain...
computer science: {'input': 'When do we reach Artificial General Intelligence (AGI)?'}
> Finished chain.

'As a computer scientist, I believe that reaching Artificial General Intelligence (AGI) is a complex and multifaceted goal that involves advancements in various fields such as machine learning, natural language processing, robotics, and cognitive science. While there is no definitive answer to when we will reach AGI, many experts predict that it could happen within the next few decades as technology continues to advance at a rapid pace.\n\nAGI refers to a machine that possesses the ability to understand, learn, and apply knowledge in a way that is indistinguishable from human intelligence. Achieving AGI would require machines to not only perform specific tasks but also adapt to new situations, learn from experience, and exhibit creativity and problem-solving capabilities.\n\nIn order to reach AGI, researchers and scientists must continue to push the boundaries of artificial intelligence and develop more sophisticated algorithms and models that can mimic the complexities of human intelligence. Collaboration, innovation, and ethical considerations will also play a crucial role in the development of AGI.\n\nOverall, while the timeline for achieving AGI is uncertain, the advancements in technology and the dedication of the scientific community make it a realistic possibility in the near future.'

In [109]:
chain.run("Why is the sky blue?")

> Entering new MultiPromptChain chain...
physics: {'input': 'Why is the sky blue?'}
> Finished chain.

"The sky appears blue because of the way sunlight interacts with the Earth's atmosphere. When sunlight reaches the Earth's atmosphere, it is made up of different colors of light, each with a different wavelength. The shorter wavelengths, such as blue and violet, are scattered more easily by the gases and particles in the atmosphere. This scattering causes the blue light to be scattered in all directions, making the sky appear blue to our eyes."

**Repeat the above at least once for different inputs and chains executions - Be creative!**