<a href="https://colab.research.google.com/github/Affiwhizz/lab-chains-in-langchain/blob/main/lab-chains-in-langchain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab | Chains in LangChain

## Outline

* LLMChain
* Sequential Chains
  * SimpleSequentialChain
  * SequentialChain
* Router Chain

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import os
from getpass import getpass

if not os.getenv("OPENAI_API_KEY"):
    os.environ["OPENAI_API_KEY"] = getpass("Paste your OpenAI API key here (won't show): ")

if not os.getenv("HUGGINGFACEHUB_API_TOKEN"):
    os.environ["HUGGINGFACEHUB_API_TOKEN"] = getpass("Paste your Hugging Face token here (won't show): ")

print("Keys successfully loaded (hidden safely).")

Paste your OpenAI API key here (won't show): ··········
Paste your Hugging Face token here (won't show): ··········
Keys successfully loaded (hidden safely).

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
#!pip install pandas

In [6]:
# 1) Create a data folder (optional)
!mkdir -p lab/data

!wget -O lab/data/Data.csv "https://raw.githubusercontent.com/Affiwhizz/lab-chains-in-langchain/refs/heads/main/data/Data.csv"

import pandas as pd
df = pd.read_csv("lab/data/Data.csv")
df.head()

--2025-10-10 11:47:27--  https://raw.githubusercontent.com/Affiwhizz/lab-chains-in-langchain/refs/heads/main/data/Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2524 (2.5K) [text/plain]
Saving to: ‘lab/data/Data.csv’

lab/data/Data.csv   100%[===================>]   2.46K  --.-KB/s    in 0s

2025-10-10 11:47:27 (29.3 MB/s) - ‘lab/data/Data.csv’ saved [2524/2524]

                   Product                                             Review
0     Queen Size Sheet Set  I ordered a king size set. My only criticism w...
1   Waterproof Phone Pouch  I loved the waterproof sac, although the openi...
2      Luxury Air Mattress  This mattress had a small hole in the top of i...
3           Pillows Insert  This is the best throw pillow fillers on Amazo...
4  Milk Frother Handheld\n   I loved this product. But they only seem to l...

In [7]:
import pandas as pd
df = pd.read_csv('./lab/data/Data.csv')

In [36]:
df.head()

                   Product                                             Review
0     Queen Size Sheet Set  I ordered a king size set. My only criticism w...
1   Waterproof Phone Pouch  I loved the waterproof sac, although the openi...
2      Luxury Air Mattress  This mattress had a small hole in the top of i...
3           Pillows Insert  This is the best throw pillow fillers on Amazo...
4  Milk Frother Handheld\n   I loved this product. But they only seem to l...

## LLMChain

In [9]:
!pip install -q "requests==2.32.5"
!pip install -qU "langchain==0.3.27" "langchain-community==0.3.31" "langchain-openai==0.2.12" "openai>=1.44.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 4.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 69.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.8/449.8 kB 30.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.6 MB/s eta 0:00:00

In [10]:
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains import LLMChain

In [11]:
#Replace None by your own value and justify
llm = ChatOpenAI(temperature=0.7)

In [12]:
prompt = ChatPromptTemplate.from_template(
    "Write a query that would take a variable to describe any product: {product}"
)

In [13]:

chain = LLMChain(llm=llm, prompt=prompt)

/tmp/ipython-input-546483037.py:1: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  chain = LLMChain(llm=llm, prompt=prompt)

In [14]:
product = "Pillow Insert"
response = chain.run(product=product)
print(response)

/tmp/ipython-input-2223663158.py:2: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  response = chain.run(product=product)

SELECT *
FROM products
WHERE product_name = 'Pillow Insert';

## SimpleSequentialChain

In [15]:
from langchain.chains import SimpleSequentialChain

In [16]:
llm = ChatOpenAI(temperature=0.9)

# prompt template 1
first_prompt = ChatPromptTemplate.from_template(
    "Repeat the initial query or create a new query that would feed into the second prompt. Query: {query}"
)

# Chain 1
chain_one = LLMChain(llm=llm, prompt=first_prompt)

In [17]:
# prompt template 2
second_prompt = ChatPromptTemplate.from_template(
    "Write the second prompt query that takes an input variable whose input will come from the previous prompt: {query}"
)

# chain 2
chain_two = LLMChain(llm=llm, prompt=second_prompt)

In [18]:
overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],
                                             verbose=True
                                            )

In [19]:
overall_simple_chain.run(product)

> Entering new SimpleSequentialChain chain...
New query: What are the different sizes and materials available for pillow inserts?
Please input the type of pillow insert you are interested in (e.g. square, lumbar, round) based on your previous response.

> Finished chain.

'Please input the type of pillow insert you are interested in (e.g. square, lumbar, round) based on your previous response.'

**Repeat the above twice for different products**

## SequentialChain

In [20]:
from langchain.chains import SequentialChain

In [21]:
llm = ChatOpenAI(temperature=0.9)


first_prompt = ChatPromptTemplate.from_template(
  "Translate the following review into Portuguese: {review}"
)

chain_one = LLMChain(llm=llm, prompt=first_prompt,
                     output_key="Portuguese_review"
                    )

In [22]:
second_prompt = ChatPromptTemplate.from_template(
    "Summarize the following product review in one concise paragraph: {Portuguese_review}"
)

chain_two = LLMChain(
    llm=llm,
    prompt=second_prompt,
    output_key="summary"
)

In [23]:
third_prompt = ChatPromptTemplate.from_template(
    "Translate the following summary into {language}: {summary}"
)

chain_three = LLMChain(
    llm=llm,
    prompt=third_prompt,
    output_key="translated_summary"
)

In [24]:
# prompt template 4: follow-up message that takes as inputs the two previous results
fourth_prompt = ChatPromptTemplate.from_template(
    "Using the Portuguese review and its summary, write a polite follow-up message "
    "asking for any missing details.\n\n"
    "Portuguese review:\n{Portuguese_review}\n\n"  # ← changed here
    "Summary:\n{summary}"
)

chain_four = LLMChain(
    llm=llm,
    prompt=fourth_prompt,
    output_key="followup_message"
)

In [25]:
# overall_chain: input= Review
# and output= English_Review,summary, followup_message
overall_chain = SequentialChain(
    chains=[chain_one, chain_two, chain_three, chain_four],
    input_variables=["review", "language"],
    output_variables=["Portuguese_review", "summary", "followup_message"],
    verbose=True
)

In [26]:
review_text = str(df.Review[5])
result = overall_chain({
    "review": review_text,
    "language": "Portuguese"
})

/tmp/ipython-input-2531750076.py:2: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  result = overall_chain({

> Entering new SequentialChain chain...

> Finished chain.

In [27]:
for key, value in result.items():
    print(f"\n--- {key.upper()} ---\n{value}")

--- REVIEW ---
Je trouve le goût médiocre. La mousse ne tient pas, c'est bizarre. J'achète les mêmes dans le commerce et le goût est bien meilleur...
Vieux lot ou contrefaçon !?

--- LANGUAGE ---
Portuguese

--- PORTUGUESE_REVIEW ---
Acho o sabor medíocre. A espuma não dura, é estranho. Compro os mesmos no comércio e o sabor é muito melhor... Lote antigo ou falsificação !?

--- SUMMARY ---
O revisor acha o sabor do produto medíocre e não gosta da falta de durabilidade da espuma. Eles afirmam que o sabor é melhor quando comprado em outro lugar e sugerem que o produto pode ser de um lote antigo ou falsificado.

--- FOLLOWUP_MESSAGE ---
Caro(a) revisor(a),

Espero que esteja bem. Gostaria de agradecer pelo seu feedback sobre o nosso produto. No entanto, percebi que você mencionou que o sabor é melhor quando comprado em outro lugar e levantou a possibilidade de o produto ser de um lote antigo ou falsificado. Será que você poderia fornecer mais detalhes sobre onde costuma adquirir o produto e se notou alguma diferença no rótulo ou na embalagem que poderia indicar uma possível falsificação?

Agradeço desde já pela sua colaboração e estou à disposição para esclarecer qualquer dúvida que possa surgir.

Atenciosamente, [Seu Nome]

**Repeat the above twice for different products or reviews**

## Router Chain

In [28]:
physics_template = """You are a very smart physics professor. \
You are great at answering questions about physics in a concise\
and easy to understand manner. \
When you don't know the answer to a question you admit\
that you don't know.

Here is a question:
{input}"""


math_template = """You are a very good mathematician. \
You are great at answering math questions. \
You are so good because you are able to break down \
hard problems into their component parts,
answer the component parts, and then put them together\
to answer the broader question.

Here is a question:
{input}"""

history_template = """You are a very good historian. \
You have an excellent knowledge of and understanding of people,\
events and contexts from a range of historical periods. \
You have the ability to think, reflect, debate, discuss and \
evaluate the past. You have a respect for historical evidence\
and the ability to make use of it to support your explanations \
and judgements.

Here is a question:
{input}"""


computerscience_template = """ You are a successful computer scientist.\
You have a passion for creativity, collaboration,\
forward-thinking, confidence, strong problem-solving capabilities,\
understanding of theories and algorithms, and excellent communication \
skills. You are great at answering coding questions. \
You are so good because you know how to solve a problem by \
describing the solution in imperative steps \
that a machine can easily interpret and you know how to \
choose a solution that has a good balance between \
time complexity and space complexity.

Here is a question:
{input}"""

biology_template = """You are an excellent biologist. \
You have a deep understanding of living organisms, \
from the molecular and cellular level to entire ecosystems. \
You are skilled at observing patterns in nature, analyzing biological data, \
and explaining complex processes like evolution, genetics, physiology, and ecology. \
You can clearly communicate how life functions and adapts, \
and you make connections between different biological concepts \
to answer challenging questions.

Here is a question:
{input}"""

In [29]:
prompt_infos = [
    {
        "name": "physics",
        "description": "Good for answering questions about physics",
        "prompt_template": physics_template
    },
    {
        "name": "math",
        "description": "Good for answering math questions",
        "prompt_template": math_template
    },
    {
        "name": "History",
        "description": "Good for answering history questions",
        "prompt_template": history_template
    },
    {
        "name": "computer science",
        "description": "Good for answering computer science questions",
        "prompt_template": computerscience_template
    },
    {
        "name": "biology",
        "description": "Good for answering biology questions",
        "prompt_template": biology_template
    }
]

In [30]:
from langchain.chains.router import MultiPromptChain
from langchain.chains.router.llm_router import LLMRouterChain,RouterOutputParser
from langchain.prompts import PromptTemplate

In [31]:
llm = ChatOpenAI(temperature=0)

In [32]:
destination_chains = {}
for p_info in prompt_infos:
    name = p_info["name"]
    prompt_template = p_info["prompt_template"]
    prompt = ChatPromptTemplate.from_template(template=prompt_template)
    chain = LLMChain(llm=llm, prompt=prompt)
    destination_chains[name] = chain

destinations = [f"{p['name']}: {p['description']}" for p in prompt_infos]
destinations_str = "\n".join(destinations)

In [33]:
default_prompt = ChatPromptTemplate.from_template("{input}")
default_chain = LLMChain(llm=llm, prompt=default_prompt)

In [34]:
MULTI_PROMPT_ROUTER_TEMPLATE = """Given a raw text input to a \
language model select the model prompt best suited for the input. \
You will be given the names of the available prompts and a \
description of what the prompt is best suited for. \
You may also revise the original input if you think that revising\
it will ultimately lead to a better response from the language model.

<< FORMATTING >>
Return a markdown code snippet with a JSON object formatted to look like:
```json
{{{{
    "destination": string \ name of the prompt to use or "DEFAULT"
    "next_inputs": string \ a potentially modified version of the original input
}}}}
```

REMEMBER: "destination" MUST be one of the candidate prompt \
names specified below OR it can be "DEFAULT" if the input is not\
well suited for any of the candidate prompts.
REMEMBER: "next_inputs" can just be the original input \
if you don't think any modifications are needed.

<< CANDIDATE PROMPTS >>
{destinations}

<< INPUT >>
{{input}}

<< OUTPUT (remember to include the ```json)>>"""

In [35]:
router_template = MULTI_PROMPT_ROUTER_TEMPLATE.format(
    destinations=destinations_str
)
router_prompt = PromptTemplate(
    template=router_template,
    input_variables=["input"],
    output_parser=RouterOutputParser(),
)

router_chain = LLMRouterChain.from_llm(llm, router_prompt)

In [36]:
chain = MultiPromptChain(router_chain=router_chain,
                         destination_chains=destination_chains,
                         default_chain=default_chain, verbose=True
                        )

/tmp/ipython-input-3038952769.py:1: LangChainDeprecationWarning: Please see migration guide here for recommended implementation: https://python.langchain.com/docs/versions/migrating_chains/multi_prompt_chain/
  chain = MultiPromptChain(router_chain=router_chain,

In [37]:
chain.run("What is black body radiation?")

> Entering new MultiPromptChain chain...
physics: {'input': 'What is black body radiation?'}
> Finished chain.

"Black body radiation refers to the electromagnetic radiation emitted by a perfect black body, which is an idealized physical body that absorbs all incident electromagnetic radiation. The radiation emitted by a black body depends only on its temperature and follows a specific distribution known as Planck's law. This radiation is characterized by a continuous spectrum of wavelengths and intensities, with the peak intensity shifting to shorter wavelengths as the temperature of the black body increases. Black body radiation plays a key role in understanding concepts such as thermal radiation and the quantization of energy in quantum mechanics."

In [38]:
chain.run("what is 2 + 2")

> Entering new MultiPromptChain chain...
math: {'input': 'what is 2 + 2'}
> Finished chain.

'The answer to 2 + 2 is 4.'

In [39]:
chain.run("Why does every cell in our body contain DNA?")

> Entering new MultiPromptChain chain...
biology: {'input': 'Why does every cell in our body contain DNA?'}
> Finished chain.

'Every cell in our body contains DNA because DNA is the genetic material that carries the instructions for the development, functioning, and reproduction of all living organisms. DNA contains the information needed to build and maintain an organism, including the proteins that make up our cells and tissues. \n\nHaving DNA in every cell ensures that each cell has the necessary genetic information to carry out its specific functions and to replicate itself accurately during cell division. This genetic information is crucial for maintaining the integrity and stability of our cells and ultimately our entire body. \n\nAdditionally, DNA is constantly being replicated and repaired in our cells to ensure that genetic information is passed on accurately to the next generation of cells. This process is essential for the growth, development, and overall health of our bodies. \n\nIn summary, every cell in our body contains DNA because it is essential for the proper functioning and maintenance of all living organisms.'

**Repeat the above at least once for different inputs and chains executions - Be creative!**

In [40]:
chain.run("Explain how gravity affects the motion of planets.")     # physics

> Entering new MultiPromptChain chain...
physics: {'input': 'Explain how gravity affects the motion of planets.'}
> Finished chain.

"Gravity is the force that attracts objects with mass towards each other. In the case of planets, gravity is what keeps them in orbit around the sun. The sun's gravity pulls the planets towards it, but because the planets are also moving tangentially to the sun, they end up in a stable orbit around it. The strength of gravity between two objects is determined by their masses and the distance between them. The larger the mass of the planet, the stronger the gravitational pull it exerts on other objects. This is why planets with larger masses, like Jupiter, have a greater influence on the motion of other objects in their vicinity."

In [41]:
chain.run("What is the integral of x^2?")                            # math

> Entering new MultiPromptChain chain...
math: {'input': 'What is the integral of x^2?'}
> Finished chain.

'The integral of x^2 is (1/3)x^3 + C, where C is the constant of integration.'

In [42]:
chain.run("Who was Cleopatra and what was her significance?")        # history

> Entering new MultiPromptChain chain...
History: {'input': 'Who was Cleopatra and what was her significance?'}
> Finished chain.

"Cleopatra was the last active ruler of the Ptolemaic Kingdom of Egypt. She was a member of the Ptolemaic dynasty, a Greek royal family that ruled Egypt after the death of Alexander the Great. Cleopatra is perhaps best known for her relationships with Julius Caesar and Mark Antony, two powerful Roman leaders.\n\nCleopatra's significance lies in her political savvy and ability to maintain power in a tumultuous time. She used her relationships with Caesar and Antony to secure her position as ruler of Egypt and to protect her kingdom from Roman interference. Cleopatra was also known for her intelligence, charisma, and beauty, which captivated both Caesar and Antony.\n\nDespite her efforts, Cleopatra's reign ultimately came to an end with the defeat of Antony and Cleopatra's forces by Octavian (later known as Augustus) at the Battle of Actium in 31 BC. Cleopatra and Antony committed suicide shortly after, marking the end of the Ptolemaic dynasty and the beginning of Roman rule in Egypt.\n\nCleopatra's legacy has endured through history, with many viewing her as a symbol of female power and resilience. She has been the subject of countless works of art, literature, and film, solidifying her place as one of the most famous and enigmatic figures of the ancient world."

In [43]:
chain.run("What is an algorithm in computer science?")               # computer science

> Entering new MultiPromptChain chain...
computer science: {'input': 'What is an algorithm in computer science?'}
> Finished chain.

'In computer science, an algorithm is a step-by-step procedure or formula for solving a problem. It is a set of instructions that are followed in order to achieve a specific task or goal. Algorithms can be expressed in various forms, such as natural language, pseudocode, or programming languages. They are essential in computer science as they provide a systematic way to solve problems efficiently and effectively. Good algorithms are designed to have a balance between time complexity (how long it takes to run) and space complexity (how much memory it uses).'

In [44]:
chain.run("How does the human heart pump blood?")                    # biology

> Entering new MultiPromptChain chain...
biology: {'input': 'How does the human heart pump blood?'}
> Finished chain.

"The human heart is a muscular organ that functions as a pump to circulate blood throughout the body. The heart is divided into four chambers: the right atrium, right ventricle, left atrium, and left ventricle. \n\nThe process of pumping blood begins with the right atrium receiving deoxygenated blood from the body through the superior and inferior vena cava. The right atrium contracts, forcing the blood into the right ventricle through the tricuspid valve. \n\nThe right ventricle then contracts, pumping the deoxygenated blood through the pulmonary valve and into the pulmonary artery, which carries the blood to the lungs for oxygenation. \n\nOxygenated blood returns to the heart through the pulmonary veins and enters the left atrium. The left atrium contracts, pushing the blood into the left ventricle through the mitral valve. \n\nThe left ventricle, being the strongest chamber of the heart, contracts and pumps the oxygenated blood through the aortic valve and into the aorta, the body's main artery. From there, the blood is distributed to the rest of the body through smaller arteries and capillaries.\n\nThis process of contraction and relaxation of the heart chambers is coordinated by electrical signals that regulate the heartbeat. The heart's rhythmic pumping action ensures that oxygen and nutrients are delivered to all cells in the body and that waste products are removed efficiently."